version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelance_exchange_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/freelance_exchange
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: freelance_exchange_db
    environment:
      POSTGRES_DB: freelance_exchange
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
